export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const DELETE_USER = 'DELETE_USER';

export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SEND_TEXT = 'SEND_TEXT';
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
export const DELETE_FEEDBACK = 'DELETE_FEEDBACK';
export const GET_PHONE_NUMBER = 'GET_PHONE_NUMBER';
export const CLEAR_NUMBER = 'CLEAR_NUMBER';
export const GET_TEXT_RECORDS = 'GET_TEXT_RECORDS';
export const GET_RECURRING_TEXTS = 'GET_RECURRING_TEXTS';
export const DELETE_TEXT = 'DELETE_TEXT';

export const ALERT = 'ALERT';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const FETCH_RESTAURANT = 'FETCH_RESTAURANT';
export const FETCH_ALL_RESTAURANTS = 'FETCH_ALL_RESTAURANTS';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const FETCH_MEAL_PROGRAM_INFO = 'FETCH_MEAL_PROGRAM_INFO';

export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';

export const GET_SHIFTS = 'GET_SHIFTS';
export const SIGN_UP_FOR_SHIFT = 'SIGN_UP_FOR_SHIFT';
export const GET_HOURS = 'GET_HOURS';
export const EDIT_HOURS = 'EDIT_HOURS';
export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_FRIDGES = 'GET_FRIDGES';

export const SUBMIT_FORM = 'SUBMIT_FORM';

export const UPLOAD_FILES = 'UPLOAD_FILES';
export const UPLOAD_IN_PROGRESS = 'UPLOAD_IN_PROGRESS';

export const GET_EVENTS = 'GET_EVENTS';
export const SIGN_UP_FOR_EVENT_SHIFT = 'SIGN_UP_FOR_EVENT_SHIFT';
export const GET_EVENT_HOURS = 'GET_EVENT_HOURS';

export const GET_MEAL_PROGRAM_SCHEDULE = 'GET_MEAL_PROGRAM_SCHEDULE';

export const GET_VOLUNTEER = 'GET_VOLUNTEER';
export const CREATE_VOLUNTEER = 'CREATE_VOLUNTEER';
